name: "Build"

on:
  push:
    branches: [main]

jobs:
  playwright-jest:
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.pnpm-store/pw-browsers
    defaults:
      run:
        shell: bash
        working-directory: jest-playwright
    name: Playwright with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ~/.pnpm-store/v3
          key: v1-${{ runner.os }}-pnpm-jp-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-jp-
      - run: pnpm i --frozen-lockfile
      - run: pnpm test

  playwright-test-runner:
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.pnpm-store/pw-browsers
    defaults:
      run:
        shell: bash
        working-directory: playwright-test
    name: Playwright test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
