name: "Quality"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  playwright-jest:
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.pnpm-store/pw-browsers
    defaults:
      run:
        shell: bash
        working-directory: jest-playwright
    name: Playwright with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 6
      - uses: actions/cache@v4
        id: pnpm-store
        with:
          path: ~/.pnpm-store/v3
          key: v1-${{ runner.os }}-pnpm-jp-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-jp-
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Failed test screenshots
          path: "jest-playwright/test-results/"
          if-no-files-found: ignore

  playwright-test-runner:
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.pnpm-store/pw-browsers
    defaults:
      run:
        shell: bash
        working-directory: playwright-test
    name: Playwright Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 6
      - run: pnpm i --frozen-lockfile
      - run: npx playwright install chromium
      - run: pnpm test
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Failed test screenshots
          path: "playwright-test/test-results/"
          if-no-files-found: ignore
